<?php

namespace AppBundle\Repository;

/**
 * CaseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
