<?php

namespace AppBundle\Repository;

/**
 * PetitionerNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetitionerNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
