<?php

namespace AppBundle\Repository;

/**
 * PetitionerNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PetitionerNumberRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOldestNewCase()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT p
                               FROM AppBundle:PetitionerNumber p
                               JOIN p.status s
                               WHERE s.name = \'New\'
                               ORDER BY p.createdOn'
                )
                ->setMaxResults(1)
                ->getSingleResult();
    }
}
