<?php

namespace AppBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewStatus()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT s FROM AppBundle:Status s WHERE s.name = \'New\'')
                ->getSingleResult();
    }

    public function getInProgressStatus()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT s FROM AppBundle:Status s WHERE s.name = \'In Progress\'')
                ->getSingleResult();
    }

    public function getAssignedStatus()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT s FROM AppBundle:Status s WHERE s.name = \'Assigned\'')
                ->getSingleResult();
    }

    public function getEndStatus()
    {
        return $this->getEntityManager()
                ->createQuery('SELECT s FROM AppBundle:Status s WHERE s.name = \'End\'')
                ->getSingleResult();
    }
}
